# Repository local hooks
repos:
  - repo: local
    hooks:
      # Typescript checking
      - id: Typescript
        name: Typescript checking
        entry: npx tsc --noEmit
        language: system
      # Linting using npm command
      - id: lint
        name: Lint code with Biome
        entry: npm run lint
        language: system
      # Format with npm command
      - id: format
        name: Format code with Biome
        entry: npm run format
        language: system
