# Repository local hooks
repos:
  - repo: local
    hooks:
      # Linting using npm command
      - id: lint
        name: Lint code with Biome
        entry: npm run lint
        language: system
      # Format with npm command
      - id: format
        name: Format code with Biome
        entry: npm run format
        language: system
